//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ticket_system
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ticket
    {
        public int TicketID { get; set; }
        public string subject { get; set; }
        public string message { get; set; }
        public int employeeID { get; set; }
        public Nullable<bool> Completed { get; set; }
    
        public virtual Login Login { get; set; }
    }
}
